version: '3.7'

services:
  app:
    container_name: mob
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8080:8080"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
